---
- name: Upgrade the system 
  become: true
  pacman:
    update_cache: yes
    upgrade: yes
 
- name: Install needed pacman packages
  become: true
  pacman:
    name:
      - bc
      - base-devel
      - asp
      - gtest 
      - jsoncpp
